services:
  db:
    image: postgres:17-alpine
    container_name: db
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5438:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - vs_network

networks:
  vs_network:
    name: vs_network

volumes:
  pgdata: